name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Github Repository
        run: |
          git config --global user.email "polarisdp@gmail.com"
          git config --global user.name "dopaemon"

      - name: Clone A1 Repository
        run: |
          git clone --depth=1 https://github.com/CydiaArchives/package_debian_A1.git

      - name: Create Packages
        run: |
          ./sync.sh
      - name: Format for Cluster Repo
        run: |
          sed -i 's|Filename: \./package_debian_A1|Filename: https://CydiaArchives.github.io/package_debian_A1|' Packages

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Repo: Repository Update"

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  gh-pages:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${\{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
